<?php
$title = 'List of categories';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('category', array('action'=>'add'));?>">Add category</a>
</p>

<?php if(count($categories) == 0) {
    print $this->escapeHtml("No category available");
} else {
?>
<table class="table">
    <tr>
        <th>Name</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($categories as $category) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($category->name);?></td>
        <td>
            <a href="<?php echo $this->url('category', array('action'=>'edit', 'id' => $category->id_category));?>">Edit</a>
            <a href="<?php echo $this->url('category', array('action'=>'delete', 'id' => $category->id_category));?>">Remove</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php } ?>